apiVersion: v1
kind: Service
metadata:
  name: chapter-07-example
  namespace: default
spec:
  type: NodePort
  selector:
    app: chapter-07-example
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30123